// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Generic specification of a source configuration file
public struct ConfigFile: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The file name of the configuration file (full or relative path).
  public var filePath: Swift.String = Swift.String()

  /// The bytes that constitute the file.
  public var fileContents: Foundation.Data = Foundation.Data()

  /// The type of configuration file this represents.
  public var fileType: ConfigFile.FileType = ConfigFile.FileType()

  /// Initialize a new instance of `ConfigFile`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConfigFile().with { $0.filePath = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public enum FileType: Codable, Equatable, Sendable {
    /// Unknown file type.
    case unspecified
    /// YAML-specification of service.
    case serviceConfigYaml
    /// OpenAPI specification, serialized in JSON.
    case openApiJson
    /// OpenAPI specification, serialized in YAML.
    case openApiYaml
    /// FileDescriptorSet, generated by protoc.
    ///
    /// To generate, use protoc with imports and source info included.
    /// For an example test.proto file, the following command would put the value
    /// in a new file named out.pb.
    ///
    /// $protoc --include_imports --include_source_info test.proto -o out.pb
    case fileDescriptorSetProto
    /// Uncompiled Proto file. Used for storage and display purposes only,
    /// currently server-side compilation is not supported. Should match the
    /// inputs to 'protoc' command used to generated FILE_DESCRIPTOR_SET_PROTO. A
    /// file of this type can only be included if at least one file of type
    /// FILE_DESCRIPTOR_SET_PROTO is included.
    case protoFile
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .serviceConfigYaml: return 1
      case .openApiJson: return 2
      case .openApiYaml: return 3
      case .fileDescriptorSetProto: return 4
      case .protoFile: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "FILE_TYPE_UNSPECIFIED"
      case .serviceConfigYaml: return "SERVICE_CONFIG_YAML"
      case .openApiJson: return "OPEN_API_JSON"
      case .openApiYaml: return "OPEN_API_YAML"
      case .fileDescriptorSetProto: return "FILE_DESCRIPTOR_SET_PROTO"
      case .protoFile: return "PROTO_FILE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:FileType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "FILE_TYPE_UNSPECIFIED": self = .unspecified
      case "SERVICE_CONFIG_YAML": self = .serviceConfigYaml
      case "OPEN_API_JSON": self = .openApiJson
      case "OPEN_API_YAML": self = .openApiYaml
      case "FILE_DESCRIPTOR_SET_PROTO": self = .fileDescriptorSetProto
      case "PROTO_FILE": self = .protoFile
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:FileType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .serviceConfigYaml
      case 2: self = .openApiJson
      case 3: self = .openApiYaml
      case 4: self = .fileDescriptorSetProto
      case 6: self = .protoFile
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .serviceConfigYaml: return try container.encode(1)
      case .openApiJson: return try container.encode(2)
      case .openApiYaml: return try container.encode(3)
      case .fileDescriptorSetProto: return try container.encode(4)
      case .protoFile: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicemanagement.v1.ConfigFile"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
