// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Response message for GenerateConfigReport method.
public struct GenerateConfigReportResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of the service this report belongs to.
  public var serviceName: Swift.String = Swift.String()

  /// ID of the service configuration this report belongs to.
  public var id: Swift.String = Swift.String()

  /// list of ChangeReport, each corresponding to comparison between two
  /// service configurations.
  public var changeReports: [ChangeReport] = []

  /// Errors / Linter warnings associated with the service definition this
  /// report
  /// belongs to.
  public var diagnostics: [Diagnostic] = []

  /// Initialize a new instance of `GenerateConfigReportResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GenerateConfigReportResponse().with { $0.serviceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicemanagement.v1.GenerateConfigReportResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
