// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for GenerateConfigReport method.
public struct GenerateConfigReportRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Service configuration for which we want to generate the report.
  /// For this version of API, the supported types are
  /// [google.api.servicemanagement.v1.ConfigRef][google.api.servicemanagement.v1.ConfigRef],
  /// [google.api.servicemanagement.v1.ConfigSource][google.api.servicemanagement.v1.ConfigSource],
  /// and [google.api.Service][google.api.Service]
  ///
  /// [google.api.Service]: https://www.google.com/search?q=Swift+google.api+GoogleApi.Service
  /// [google.api.servicemanagement.v1.ConfigRef]: <doc:ConfigRef>
  /// [google.api.servicemanagement.v1.ConfigSource]: <doc:ConfigSource>
  public var newConfig: GoogleCloudWkt.`Any`? = nil

  /// Optional. Service configuration against which the comparison will be done.
  /// For this version of API, the supported types are
  /// [google.api.servicemanagement.v1.ConfigRef][google.api.servicemanagement.v1.ConfigRef],
  /// [google.api.servicemanagement.v1.ConfigSource][google.api.servicemanagement.v1.ConfigSource],
  /// and [google.api.Service][google.api.Service]
  ///
  /// [google.api.Service]: https://www.google.com/search?q=Swift+google.api+GoogleApi.Service
  /// [google.api.servicemanagement.v1.ConfigRef]: <doc:ConfigRef>
  /// [google.api.servicemanagement.v1.ConfigSource]: <doc:ConfigSource>
  public var oldConfig: GoogleCloudWkt.`Any`? = nil

  /// Initialize a new instance of `GenerateConfigReportRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GenerateConfigReportRequest().with { $0.newConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicemanagement.v1.GenerateConfigReportRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
