// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The metadata associated with a long running operation resource.
public struct OperationMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The full name of the resources that this operation is directly
  /// associated with.
  public var resourceNames: [Swift.String] = []

  /// Detailed status information for each step. The order is undetermined.
  public var steps: [OperationMetadata.Step] = []

  /// Percentage of completion of this operation, ranging from 0 to 100.
  public var progressPercentage: Swift.Int32 = Swift.Int32()

  /// The start time of the operation.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `OperationMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OperationMetadata().with { $0.resourceNames = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Represents the status of one operation step.
  public struct Step: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The short description of the step.
    public var description: Swift.String = Swift.String()

    /// The status code.
    public var status: OperationMetadata.Status = OperationMetadata.Status()

    /// Initialize a new instance of `Step`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Step().with { $0.description = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.api.servicemanagement.v1.OperationMetadata.Step"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Code describes the status of the operation (or one of its steps).
  public enum Status: Codable, Equatable, Sendable {
    /// Unspecifed code.
    case unspecified
    /// The operation or step has completed without errors.
    case done
    /// The operation or step has not started yet.
    case notStarted
    /// The operation or step is in progress.
    case inProgress
    /// The operation or step has completed with errors. If the operation is
    /// rollbackable, the rollback completed with errors too.
    case failed
    /// The operation or step has completed with cancellation.
    case cancelled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .done: return 1
      case .notStarted: return 2
      case .inProgress: return 3
      case .failed: return 4
      case .cancelled: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATUS_UNSPECIFIED"
      case .done: return "DONE"
      case .notStarted: return "NOT_STARTED"
      case .inProgress: return "IN_PROGRESS"
      case .failed: return "FAILED"
      case .cancelled: return "CANCELLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATUS_UNSPECIFIED": self = .unspecified
      case "DONE": self = .done
      case "NOT_STARTED": self = .notStarted
      case "IN_PROGRESS": self = .inProgress
      case "FAILED": self = .failed
      case "CANCELLED": self = .cancelled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .done
      case 2: self = .notStarted
      case 3: self = .inProgress
      case 4: self = .failed
      case 5: self = .cancelled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .done: return try container.encode(1)
      case .notStarted: return try container.encode(2)
      case .inProgress: return try container.encode(3)
      case .failed: return try container.encode(4)
      case .cancelled: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicemanagement.v1.OperationMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
