// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A rollout resource that defines how service configuration versions are pushed
/// to control plane systems. Typically, you create a new version of the
/// service config, and then create a Rollout to push the service config.
public struct Rollout: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Unique identifier of this Rollout. Must be no longer than 63
  /// characters and only lower case letters, digits, '.', '_' and '-' are
  /// allowed.
  ///
  /// If not specified by client, the server will generate one. The generated id
  /// will have the form of <date><revision number>, where "date" is the create
  /// date in ISO 8601 format.  "revision number" is a monotonically increasing
  /// positive number that is reset every day for each service.
  /// An example of the generated rollout_id is '2016-02-16r1'
  public var rolloutId: Swift.String = Swift.String()

  /// Creation time of the rollout. Readonly.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// The user who created the Rollout. Readonly.
  public var createdBy: Swift.String = Swift.String()

  /// The status of this rollout. Readonly. In case of a failed rollout,
  /// the system will automatically rollback to the current Rollout
  /// version. Readonly.
  public var status: Rollout.RolloutStatus = Rollout.RolloutStatus()

  /// The name of the service associated with this Rollout.
  public var serviceName: Swift.String = Swift.String()

  /// Strategy that defines which versions of service configurations should be
  /// pushed
  /// and how they should be used at runtime.
  public var strategy: OneOf_Strategy? = nil

  /// Initialize a new instance of `Rollout`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Rollout().with { $0.rolloutId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case rolloutId = "rolloutId"
    case createTime = "createTime"
    case createdBy = "createdBy"
    case status = "status"
    case trafficPercentStrategy = "trafficPercentStrategy"
    case deleteServiceStrategy = "deleteServiceStrategy"
    case serviceName = "serviceName"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.rolloutId = try container.decode(Swift.String.self, forKey: .rolloutId)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.createdBy = try container.decode(Swift.String.self, forKey: .createdBy)
    self.status = try container.decode(Rollout.RolloutStatus.self, forKey: .status)
    self.serviceName = try container.decode(Swift.String.self, forKey: .serviceName)

    var strategy: OneOf_Strategy? = nil
    let strategyCheckAndSet = {
      if strategy != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'strategy'"))
      }
      strategy = $0
    }
    if let trafficPercentStrategy = try container.decodeIfPresent(
      Rollout.TrafficPercentStrategy?.self, forKey: .trafficPercentStrategy)
    {
      try strategyCheckAndSet(.trafficPercentStrategy(trafficPercentStrategy))
    }
    if let deleteServiceStrategy = try container.decodeIfPresent(
      Rollout.DeleteServiceStrategy?.self, forKey: .deleteServiceStrategy)
    {
      try strategyCheckAndSet(.deleteServiceStrategy(deleteServiceStrategy))
    }
    self.strategy = strategy
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.rolloutId, forKey: .rolloutId)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.createdBy, forKey: .createdBy)
    try container.encode(self.status, forKey: .status)
    try container.encode(self.serviceName, forKey: .serviceName)

    if let choice = self.strategy {
      switch choice {
      case .trafficPercentStrategy(let value):
        try container.encode(value, forKey: .trafficPercentStrategy)
      case .deleteServiceStrategy(let value):
        try container.encode(value, forKey: .deleteServiceStrategy)
      }
    }
  }

  /// Strategy that specifies how clients of Google Service Controller want to
  /// send traffic to use different config versions. This is generally
  /// used by API proxy to split traffic based on your configured percentage for
  /// each config version.
  ///
  /// One example of how to gradually rollout a new service configuration using
  /// this
  /// strategy:
  /// Day 1
  ///
  ///     Rollout {
  ///       id: "example.googleapis.com/rollout_20160206"
  ///       traffic_percent_strategy {
  ///         percentages: {
  ///           "example.googleapis.com/20160201": 70.00
  ///           "example.googleapis.com/20160206": 30.00
  ///         }
  ///       }
  ///     }
  ///
  /// Day 2
  ///
  ///     Rollout {
  ///       id: "example.googleapis.com/rollout_20160207"
  ///       traffic_percent_strategy: {
  ///         percentages: {
  ///           "example.googleapis.com/20160206": 100.00
  ///         }
  ///       }
  ///     }
  public struct TrafficPercentStrategy: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Maps service configuration IDs to their corresponding traffic percentage.
    /// Key is the service configuration ID, Value is the traffic percentage
    /// which must be greater than 0.0 and the sum must equal to 100.0.
    public var percentages: [Swift.String: Swift.Double] = [:]

    /// Initialize a new instance of `TrafficPercentStrategy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TrafficPercentStrategy().with { $0.percentages = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.api.servicemanagement.v1.Rollout.TrafficPercentStrategy"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Strategy used to delete a service. This strategy is a placeholder only
  /// used by the system generated rollout to delete a service.
  public struct DeleteServiceStrategy: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `DeleteServiceStrategy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DeleteServiceStrategy().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.api.servicemanagement.v1.Rollout.DeleteServiceStrategy"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Status of a Rollout.
  public enum RolloutStatus: Codable, Equatable, Sendable {
    /// No status specified.
    case unspecified
    /// The Rollout is in progress.
    case inProgress
    /// The Rollout has completed successfully.
    case success
    /// The Rollout has been cancelled. This can happen if you have overlapping
    /// Rollout pushes, and the previous ones will be cancelled.
    case cancelled
    /// The Rollout has failed and the rollback attempt has failed too.
    case failed
    /// The Rollout has not started yet and is pending for execution.
    case pending
    /// The Rollout has failed and rolled back to the previous successful
    /// Rollout.
    case failedRolledBack
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .inProgress: return 1
      case .success: return 2
      case .cancelled: return 3
      case .failed: return 4
      case .pending: return 5
      case .failedRolledBack: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ROLLOUT_STATUS_UNSPECIFIED"
      case .inProgress: return "IN_PROGRESS"
      case .success: return "SUCCESS"
      case .cancelled: return "CANCELLED"
      case .failed: return "FAILED"
      case .pending: return "PENDING"
      case .failedRolledBack: return "FAILED_ROLLED_BACK"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RolloutStatus/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ROLLOUT_STATUS_UNSPECIFIED": self = .unspecified
      case "IN_PROGRESS": self = .inProgress
      case "SUCCESS": self = .success
      case "CANCELLED": self = .cancelled
      case "FAILED": self = .failed
      case "PENDING": self = .pending
      case "FAILED_ROLLED_BACK": self = .failedRolledBack
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RolloutStatus/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .inProgress
      case 2: self = .success
      case 3: self = .cancelled
      case 4: self = .failed
      case 5: self = .pending
      case 6: self = .failedRolledBack
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .inProgress: return try container.encode(1)
      case .success: return try container.encode(2)
      case .cancelled: return try container.encode(3)
      case .failed: return try container.encode(4)
      case .pending: return try container.encode(5)
      case .failedRolledBack: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Strategy that defines which versions of service configurations should be
  /// pushed
  /// and how they should be used at runtime.
  public enum OneOf_Strategy: Codable, Equatable, Sendable {
    /// Google Service Control selects service configurations based on
    /// traffic percentage.
    indirect case trafficPercentStrategy(Rollout.TrafficPercentStrategy?)
    /// The strategy associated with a rollout to delete a `ManagedService`.
    /// Readonly.
    indirect case deleteServiceStrategy(Rollout.DeleteServiceStrategy?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.api.servicemanagement.v1.Rollout"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
