// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
import GoogleCloudWkt
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol ServiceManagerStub {
    func listServices(
      request: ListServicesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiServiceManagementV1.ListServicesResponse

    func getService(
      request: GetServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiServiceManagementV1.ManagedService

    func createService(
      request: CreateServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteService(
      request: DeleteServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func undeleteService(
      request: UndeleteServiceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listServiceConfigs(
      request: ListServiceConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiServiceManagementV1.ListServiceConfigsResponse

    func getServiceConfig(
      request: GetServiceConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.Service

    func createServiceConfig(
      request: CreateServiceConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApi.Service

    func submitConfigSource(
      request: SubmitConfigSourceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listServiceRollouts(
      request: ListServiceRolloutsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiServiceManagementV1.ListServiceRolloutsResponse

    func getServiceRollout(
      request: GetServiceRolloutRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiServiceManagementV1.Rollout

    func createServiceRollout(
      request: CreateServiceRolloutRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func generateConfigReport(
      request: GenerateConfigReportRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleApiServiceManagementV1.GenerateConfigReportResponse

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }
}
