// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleApi
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class ServiceManagerLogging: ServiceManagerStub {
    let inner: any ServiceManagerStub
    let logger: Logger

    public init(_ inner: any ServiceManagerStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-api-servicemanagement-v1"
      logger[metadataKey: "gcp.client.service"] = "servicemanagement"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ServiceManager"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listServices(
      request: ListServicesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApiServiceManagementV1.ListServicesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listServices",
        action: {
          (r: ListServicesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleApiServiceManagementV1.ListServicesResponse
          in
          return try await self.inner.listServices(request: r, options: o)
        })
    }

    public func getService(
      request: GetServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApiServiceManagementV1.ManagedService {
      try await self._intercept(
        request: request,
        options: options,
        name: "getService",
        action: {
          (r: GetServiceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleApiServiceManagementV1.ManagedService
          in
          return try await self.inner.getService(request: r, options: o)
        })
    }

    public func createService(
      request: CreateServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createService",
        action: {
          (r: CreateServiceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createService(request: r, options: o)
        })
    }

    public func deleteService(
      request: DeleteServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteService",
        action: {
          (r: DeleteServiceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteService(request: r, options: o)
        })
    }

    public func undeleteService(
      request: UndeleteServiceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "undeleteService",
        action: {
          (r: UndeleteServiceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.undeleteService(request: r, options: o)
        })
    }

    public func listServiceConfigs(
      request: ListServiceConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApiServiceManagementV1.ListServiceConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listServiceConfigs",
        action: {
          (r: ListServiceConfigsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleApiServiceManagementV1.ListServiceConfigsResponse
          in
          return try await self.inner.listServiceConfigs(request: r, options: o)
        })
    }

    public func getServiceConfig(
      request: GetServiceConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.Service {
      try await self._intercept(
        request: request,
        options: options,
        name: "getServiceConfig",
        action: {
          (r: GetServiceConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleApi.Service
          in
          return try await self.inner.getServiceConfig(request: r, options: o)
        })
    }

    public func createServiceConfig(
      request: CreateServiceConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApi.Service {
      try await self._intercept(
        request: request,
        options: options,
        name: "createServiceConfig",
        action: {
          (r: CreateServiceConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleApi.Service
          in
          return try await self.inner.createServiceConfig(request: r, options: o)
        })
    }

    public func submitConfigSource(
      request: SubmitConfigSourceRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "submitConfigSource",
        action: {
          (r: SubmitConfigSourceRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.submitConfigSource(request: r, options: o)
        })
    }

    public func listServiceRollouts(
      request: ListServiceRolloutsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApiServiceManagementV1.ListServiceRolloutsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listServiceRollouts",
        action: {
          (r: ListServiceRolloutsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleApiServiceManagementV1.ListServiceRolloutsResponse
          in
          return try await self.inner.listServiceRollouts(request: r, options: o)
        })
    }

    public func getServiceRollout(
      request: GetServiceRolloutRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApiServiceManagementV1.Rollout {
      try await self._intercept(
        request: request,
        options: options,
        name: "getServiceRollout",
        action: {
          (r: GetServiceRolloutRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleApiServiceManagementV1.Rollout
          in
          return try await self.inner.getServiceRollout(request: r, options: o)
        })
    }

    public func createServiceRollout(
      request: CreateServiceRolloutRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createServiceRollout",
        action: {
          (r: CreateServiceRolloutRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createServiceRollout(request: r, options: o)
        })
    }

    public func generateConfigReport(
      request: GenerateConfigReportRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleApiServiceManagementV1.GenerateConfigReportResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "generateConfigReport",
        action: {
          (r: GenerateConfigReportRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleApiServiceManagementV1.GenerateConfigReportResponse
          in
          return try await self.inner.generateConfigReport(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
